blank_issues_enabled: false
contact_links:
  - name: ğŸ™‹ğŸ¾ğŸ™‹ğŸ¼â€ Need help? Ask in Zuri Chat Community Forum
    url: https://github.com/zurichat/zc_main/discussions
    about: Feel free to ask and answer questions here